# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
workspace 'MainProject'

def share_pods
  pod 'RxSwift'
end


target 'MainProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  share_pods
  # Pods for MainProject

  target 'MainProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MainProjectUITests' do
    # Pods for testing
  end

end

target 'Hero' do
#  use_frameworks!
  project '../Poc-Module/Hero/Hero'
  share_pods
end
